### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Triloworld** [adampata89/MagentoDeliveryDate#1]
Hello, after we get CV we like to check code.
What we see is good one but with some very important flaw.
List to consideration for rewriting code:
- This line  contain ObjectManager with can be rewrite to testable module: https://github.com/adampata89/MagentoDeliveryDate/blob/3aace54d8026f5a2f612b0e6756d1c708dcabf23/Deliverydate/Model/Observer/AddHtmlToOrderShippingViewObserver.php#L14
Article about why not and all details: https://magento.stackexchange.com/questions/117098/to-use-or-not-to-use-the-objectmanager-directly

- Overriding JS files is banned:
https://github.com/adampata89/MagentoDeliveryDate/blob/3aace54d8026f5a2f612b0e6756d1c708dcabf23/Deliverydate/view/frontend/web/js/shipping-save-processor-default-override.js
This is ready to go solution form M2.2 where is fix apply to easily extend it:
https://magento.stackexchange.com/questions/228645/extention-attributes-in-payload-return-as-null-in-backend
This cause troubles in many version of magento 2 and with more modules trying to do that in same way (this won't be composable). There is possibility to extend It and use _super() and mixins syntax in `require-config.js`. 
Example : https://magento.stackexchange.com/a/292728

- Composer usage, version set, releases cycle. This will show that you can implement one small module in production setup.
Every demo when I see is "one time usage" where every work is "continuous integration". This can be main factor if somebody can automate in GitHub Action and know how to use branch. Even better - you can customize your workflow to your needs and help yourself (auto code analysis or tests that aren't in this module)

Checked code syntax is missing Exceptions message, but logic is very good. Usage of proper extending layout, plugins and api is good one. Example of production good code: https://github.com/adampata89/MagentoDeliveryDate/blob/3aace54d8026f5a2f612b0e6756d1c708dcabf23/Deliverydate/Model/DeliverydateRepository.php 
I'am not specialist to code of backend module in some weird case but this is even by best one fixed in cycles rather than one time so code in this level is enough to be proud of :) 

Overall: 7.5/10 (1 less for overrides, 1 less for composer and releases stuff like tags and information/automation and 0.5 for even trying some tests scenario). 

Consider adding MIT license as I don't do code review without it (Love Open Source, if module is demo then license help other to learn and my time isn't wasted for free on some stuff that is licensed to company and this can violate any regulations, even you can give my troubles so pleas add it always. You can always change - this will point what code was open and in on what point of time isn't and license is changed)

I hope It helps as much as I can :)
After read you can close issue and do small one and use that as "epic" one :)

**Comment by adampata89** [comment]
Hi,
Thank's for your time, codereview and comments


śr., 27 kwi 2022, 12:10 użytkownik Patryk Padus ***@***.***>
napisał:
